# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\autoscroll.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(400, 300))
        mainWindow.setMaximumSize(QtCore.QSize(600, 400))
        mainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        mainWindow.setAutoFillBackground(True)
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 80, 291, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scroll_disance_babel = QtWidgets.QLabel(self.layoutWidget)
        self.scroll_disance_babel.setObjectName("scroll_disance_babel")
        self.horizontalLayout_2.addWidget(self.scroll_disance_babel)
        self.scroll_distance = QtWidgets.QSpinBox(self.layoutWidget)
        self.scroll_distance.setMinimum(10)
        self.scroll_distance.setMaximum(1000)
        self.scroll_distance.setSingleStep(100)
        self.scroll_distance.setObjectName("scroll_distance")
        self.horizontalLayout_2.addWidget(self.scroll_distance)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 30, 291, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scroll_timing_label = QtWidgets.QLabel(self.layoutWidget1)
        self.scroll_timing_label.setObjectName("scroll_timing_label")
        self.horizontalLayout.addWidget(self.scroll_timing_label)
        self.scroll_timing = QtWidgets.QSpinBox(self.layoutWidget1)
        self.scroll_timing.setMinimum(1)
        self.scroll_timing.setMaximum(3)
        self.scroll_timing.setObjectName("scroll_timing")
        self.horizontalLayout.addWidget(self.scroll_timing)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 561, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_3.addWidget(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_3.addWidget(self.stop_btn)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.start_btn.clicked.connect(mainWindow.start) # type: ignore
        self.stop_btn.clicked.connect(mainWindow.stop) # type: ignore
        self.scroll_distance.valueChanged['int'].connect(mainWindow.scroll_distance_edited) # type: ignore
        self.scroll_timing.valueChanged['int'].connect(mainWindow.scroll_timing_edited) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "爬虫自动滚动工具"))
        self.groupBox.setTitle(_translate("mainWindow", "设置"))
        self.scroll_disance_babel.setText(_translate("mainWindow", "每次滚动距离:"))
        self.scroll_timing_label.setText(_translate("mainWindow", "滚动间隔时长:"))
        self.start_btn.setText(_translate("mainWindow", "开始"))
        self.stop_btn.setText(_translate("mainWindow", "暂停"))
